services:

  mandat-lib-components:
    build:
      context: ./libs/components
      dockerfile: ../../Dockerfile-lib

  mandat-lib-composables:
    build:
      context: ./libs/composables
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-interop:
    build:
      context: ./libs/solid-interop
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-oidc:
    build:
      context: ./libs/solid-oidc
      dockerfile: ../../Dockerfile-lib

  mandat-lib-solid-requests:
    build:
      context: ./libs/solid-requests
      dockerfile: ../../Dockerfile-lib

  mandat-lib-theme:
    build:
      context: ./libs/theme
      dockerfile: ../../Dockerfile-lib

  mandat-lib-utils:
    build:
      context: ./libs/utils
      dockerfile: ../../Dockerfile-lib
